name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          } else {
            echo "No requirements.txt found"
          }

      - name: Run tests
        run: |
          if (Test-Path pytest.ini) {
            pytest
          } else {
            echo "No tests found, skipping..."
          }